import RPC from "bare-rpc";
import spawn, {
  type ChildProcess as BareChildProcess,
} from "bare-runtime/spawn";
import type { Duplex, DuplexEvents } from "bare-stream";
import { randomBytes } from "node:crypto";
import { existsSync, unlinkSync } from "node:fs";
import { createServer } from "node:net";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { initializeConfig } from "@/client/init-hooks";
import { resolveConfig } from "@/client/config-loader/resolve-config.node";
import { getClientLogger } from "@/logging";
import type { RuntimeContext } from "@/schemas";

const logger = getClientLogger();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

let rpcInstance: RPC | null = null;
let rpcPromise: Promise<RPC> | null = null;
let bareWorkerProc: BareChildProcess | null = null;
let ipcServer: ReturnType<typeof createServer> | null = null;
let currentSocketPath: string | null = null;
let closePromise: Promise<void> | null = null;

/**
 * Find project root by looking for package.json (sync version)
 * Safe to call at module load time
 */
function findProjectRootSync(): string | undefined {
  let dir = process.cwd();
  const root = path.parse(dir).root;

  while (dir !== root) {
    if (fs.existsSync(path.join(dir, "package.json"))) {
      return dir;
    }
    dir = path.dirname(dir);
  }

  return undefined;
}

function getResourcesPathSync(): string | undefined {
  const { resourcesPath } = process as { resourcesPath?: string };
  return typeof resourcesPath === "string" ? resourcesPath : undefined;
}

function resolvePackagedWorkerPath(): string | undefined {
  const resourcesPath = getResourcesPathSync();
  if (!resourcesPath) return undefined;

  const candidates = [
    path.join(resourcesPath, "app.asar.unpacked", "qvac", "worker.entry.mjs"),
    path.join(resourcesPath, "app", "qvac", "worker.entry.mjs"),
    path.join(resourcesPath, "qvac", "worker.entry.mjs"),
  ];

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return candidate;
  }

  return undefined;
}

/**
 * Get default worker path from SDK dist
 */
function getDefaultWorkerPath(): string {
  const packagedWorker = path.resolve(__dirname, "../../server/worker.js");
  if (fs.existsSync(packagedWorker)) return packagedWorker;

  // Dev/source layout fallback
  return path.resolve(__dirname, "../../dist/server/worker.js");
}

/**
 * Resolve worker path with priority:
 * 1. QVAC_WORKER_PATH environment variable
 * 2. Packaged Electron app worker entry
 * 3. qvac/worker.entry.mjs in project root (generated by npx qvac bundle sdk)
 * 4. Default SDK worker
 */
function resolveWorkerPath(): string {
  const envWorkerPath = process.env["QVAC_WORKER_PATH"] as string | undefined;
  if (envWorkerPath) {
    const normalized = path.resolve(envWorkerPath);
    if (fs.existsSync(normalized)) {
      logger.info(`🔧 Using worker entry from QVAC_WORKER_PATH: ${normalized}`);
      return normalized;
    }
    logger.warn(
      `⚠️ QVAC_WORKER_PATH was set but file was not found: ${normalized}. Falling back.`,
    );
  }

  // Prefer packaged worker entry when running as a packaged Electron app.
  // This avoids accidental coupling to the project's cwd, and ensures the
  // bare worker reads JS modules from the filesystem (not app.asar).
  const packagedWorker = resolvePackagedWorkerPath();
  if (packagedWorker) {
    logger.info(`🔧 Using packaged worker entry: ${packagedWorker}`);
    return packagedWorker;
  }

  // Check for custom worker entry at project root
  // Note: We use worker.entry.mjs (unbundled ESM) for desktop because bare can
  // load ES modules directly. The packed bundle is for mobile only.
  const projectRoot = findProjectRootSync();
  if (projectRoot) {
    const customEntry = path.join(projectRoot, "qvac", "worker.entry.mjs");
    if (fs.existsSync(customEntry)) {
      logger.info(`🔧 Using custom worker entry: ${customEntry}`);
      return customEntry;
    }
  }

  // Fallback to default SDK worker
  const defaultPath = getDefaultWorkerPath();
  logger.debug(`🔧 Using default SDK worker: ${defaultPath}`);
  return defaultPath;
}

const WORKER_PATH = resolveWorkerPath();

function createSocketPath() {
  const timestamp = Date.now().toString(36);
  const randomSuffix = randomBytes(2).toString("hex");
  const socketName = `qvac-worker-${process.pid}-${timestamp}-${randomSuffix}`;
  return process.platform === "win32"
    ? `\\\\.\\pipe\\${socketName}`
    : path.join(os.tmpdir(), `${socketName}.sock`);
}

function bestEffortUnlinkSocket(socketPath: string | null) {
  // Windows named pipes are not filesystem paths, so unlink is Unix-only.
  if (!socketPath || process.platform === "win32") return;
  try {
    if (existsSync(socketPath)) {
      unlinkSync(socketPath);
    }
  } catch (error) {
    logger.debug("Failed to unlink IPC socket path", { socketPath, error });
  }
}

function snapshotAndResetState() {
  const workerToClose = bareWorkerProc;
  const serverToClose = ipcServer;
  const socketPathToClose = currentSocketPath;

  rpcInstance = null;
  rpcPromise = null;
  bareWorkerProc = null;
  ipcServer = null;
  currentSocketPath = null;

  return { workerToClose, serverToClose, socketPathToClose };
}

function closeSyncForExit() {
  const { workerToClose, serverToClose, socketPathToClose } =
    snapshotAndResetState();

  if (workerToClose) {
    try {
      workerToClose.kill("SIGTERM");
    } catch (error) {
      logger.debug("Failed to kill bare worker during process exit", { error });
    }
  }

  if (serverToClose) {
    try {
      serverToClose.close();
    } catch (error) {
      logger.debug("Failed to close IPC server during process exit", { error });
    }
  }

  bestEffortUnlinkSocket(socketPathToClose);
}

async function ensureRPC(): Promise<RPC> {
  if (rpcInstance) return rpcInstance;
  if (rpcPromise) return rpcPromise;
  if (closePromise) {
    await closePromise;
  }

  const socketPath = createSocketPath();
  currentSocketPath = socketPath;

  rpcPromise = new Promise((resolve, reject) => {
    ipcServer = createServer((socket) => {
      rpcInstance = new RPC(
        socket as unknown as Duplex<DuplexEvents>,
        () => {},
      );
      resolve(rpcInstance);
    });

    ipcServer.on("error", (error) => {
      rpcPromise = null;
      rpcInstance = null;
      bareWorkerProc = null;
      ipcServer = null;
      currentSocketPath = null;
      reject(error);
    });

    ipcServer.listen(socketPath, () => {
      bareWorkerProc = spawn("bare", {
        args: [
          WORKER_PATH,
          JSON.stringify({
            QVAC_IPC_SOCKET_PATH: socketPath,
            HOME_DIR: os.homedir(),
          }),
        ],
        stdio: ["inherit", "inherit", "inherit"],
      });
    });
  });

  const rpc = await rpcPromise;

  const runtimeContext: RuntimeContext = {
    runtime: "node",
    platform: process.platform as "darwin" | "linux" | "win32",
  };
  await initializeConfig(rpc, resolveConfig, runtimeContext);

  return rpc;
}

export async function getRPC() {
  return ensureRPC();
}

export async function createDuplexSession(payload: string, commandId: number) {
  const rpc = await ensureRPC();
  const req = rpc.request(commandId);
  const requestStream = req.createRequestStream();
  const responseStream = req.createResponseStream({ encoding: "utf-8" });
  requestStream.write(payload, "utf-8");
  return { requestStream, responseStream };
}

export async function close() {
  if (closePromise) {
    await closePromise;
    return;
  }

  if (!rpcInstance && !rpcPromise && !bareWorkerProc && !ipcServer) return;

  logger.info("🧹 Closing RPC client");

  const { workerToClose, serverToClose, socketPathToClose } =
    snapshotAndResetState();

  closePromise = (async () => {
    if (workerToClose) {
      logger.info("🐻🔫 Killing bare worker process");
      try {
        workerToClose.kill("SIGTERM");
      } catch (error) {
        logger.debug("Failed to kill bare worker process", { error });
      }
    }

    if (serverToClose) {
      logger.info("🔌 Closing IPC server");
      await new Promise<void>((resolve) => {
        try {
          serverToClose.close(() => resolve());
        } catch (error) {
          logger.debug("Failed to close IPC server", { error });
          resolve();
        }
      });
    }

    bestEffortUnlinkSocket(socketPathToClose);
  })();

  try {
    await closePromise;
  } finally {
    closePromise = null;
  }
}

function handleTerminationSignal(signal: NodeJS.Signals) {
  logger.info(`Received ${signal}, closing RPC resources...`);
  closeSyncForExit();
  process.kill(process.pid, signal);
}

process.once("SIGINT", () => handleTerminationSignal("SIGINT"));
process.once("SIGTERM", () => handleTerminationSignal("SIGTERM"));
process.once("SIGHUP", () => handleTerminationSignal("SIGHUP"));
process.once("exit", closeSyncForExit);
