import { generateExportName } from "./naming";
import type { ProcessedModel } from "./types";

export function generateModelsFileContent(models: ProcessedModel[]): string {
  const usedNames = new Set<string>();

  const modelsWithNames = models.map((m) => ({
    ...m,
    name: generateExportName({
      path: m.registryPath,
      engine: m.engine,
      name: m.modelName,
      quantization: m.quantization,
      params: m.params,
      tags: m.tags,
      usedNames,
    }),
  }));

  return generateFileContentWithNames(modelsWithNames);
}

function generateFileContentWithNames(
  modelsWithNames: (ProcessedModel & { name: string })[],
): string {
  const entries = modelsWithNames
    .map((m) => {
      const addonAlias = m.addon;
      let entry = `  {
    name: "${m.name}",
    registryPath: "${m.registryPath}",
    registrySource: "${m.registrySource}",
    blobCoreKey: "${m.blobCoreKey}",
    blobBlockOffset: ${m.blobBlockOffset},
    blobBlockLength: ${m.blobBlockLength},
    blobByteOffset: ${m.blobByteOffset},
    modelId: "${m.modelId}",
    addon: "${addonAlias}",
    expectedSize: ${m.expectedSize},
    sha256Checksum: "${m.sha256Checksum}",
    engine: "${m.engine}",
    quantization: "${m.quantization || ""}",
    params: "${m.params || ""}"`;

      if (m.shardMetadata) {
        entry += `,\n    shardMetadata: ${JSON.stringify(m.shardMetadata)}`;
      }

      entry += "\n  }";
      return entry;
    })
    .join(",\n");

  const exports = modelsWithNames
    .map((m, i) => {
      return `export const ${m.name} = {
  name: "${m.name}",
  src: \`registry://\${models[${i}].registrySource}/\${models[${i}].registryPath}\`,
  registryPath: models[${i}].registryPath,
  registrySource: models[${i}].registrySource,
  blobCoreKey: models[${i}].blobCoreKey,
  blobBlockOffset: models[${i}].blobBlockOffset,
  blobBlockLength: models[${i}].blobBlockLength,
  blobByteOffset: models[${i}].blobByteOffset,
  modelId: models[${i}].modelId,
  expectedSize: models[${i}].expectedSize,
  sha256Checksum: models[${i}].sha256Checksum,
  addon: models[${i}].addon,
  engine: models[${i}].engine,
  quantization: models[${i}].quantization,
  params: models[${i}].params,
} as const;`;
    })
    .join("\n\n");

  return `// THIS FILE IS AUTO-GENERATED BY models/update-models
// DO NOT MODIFY MANUALLY

export type RegistryItem = {
  name: string;
  registryPath: string;
  registrySource: string;
  blobCoreKey: string;
  blobBlockOffset: number;
  blobBlockLength: number;
  blobByteOffset: number;
  modelId: string;
  addon: "llm" | "whisper" | "embeddings" | "nmt" | "vad" | "tts" | "ocr" | "parakeet" | "diffusion" | "other";
  expectedSize: number;
  sha256Checksum: string;
  engine: string;
  quantization: string;
  params: string;
  shardMetadata?: readonly { 
    filename: string; 
    expectedSize: number; 
    sha256Checksum: string; 
    blobCoreKey: string; 
    blobBlockOffset: number;
    blobBlockLength: number;
    blobByteOffset: number;
  }[];
};

export type ModelConstant = {
  name: string;
  src: string;
  registryPath: string;
  registrySource: string;
  blobCoreKey: string;
  blobBlockOffset: number;
  blobBlockLength: number;
  blobByteOffset: number;
  modelId: string;
  expectedSize: number;
  sha256Checksum: string;
  addon: "llm" | "whisper" | "embeddings" | "nmt" | "vad" | "tts" | "ocr" | "parakeet" | "diffusion" | "other";
  engine: string;
  quantization: string;
  params: string;
};

export const models = [
${entries}
] as const satisfies readonly RegistryItem[];

// Individual model constants for direct import/use with loadModel
// These contain all metadata and can be used directly: loadModel({ modelSrc: WHISPER_TINY, ... })
${exports}

// Helper function to get model by name
export function getModelByName(name: string): RegistryItem | undefined {
  return models.find((model) => model.name === name);
}

// Helper function to get model by registry path
export function getModelByPath(registryPath: string): RegistryItem | undefined {
  return models.find((model) => model.registryPath === registryPath);
}

// Helper function for blob-based lookups
export function getModelBySrc(modelId: string, blobCoreKey: string): RegistryItem | undefined {
  return models.find((model) => model.modelId === modelId && model.blobCoreKey === blobCoreKey);
}
`;
}
