// This file is autogenerated by the hyperdb compiler
/* eslint-disable camelcase */

const { IndexEncoder, c } = require('hyperdb/runtime')
const { version, getEncoding, setVersion } = require('./messages.js')

const helpers0 = require('../../db-helpers.js')

// '@qvac-main-registry/license' collection key
const collection0_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 0 })

function collection0_indexify (record) {
  const a = record.spdxId
  return a === undefined ? [] : [a]
}

// '@qvac-main-registry/license' value encoding
const collection0_enc = getEncoding('@qvac-main-registry/license/hyperdb#0')

// '@qvac-main-registry/license' reconstruction function
function collection0_reconstruct (version, keyBuf, valueBuf) {
  const key = collection0_key.decode(keyBuf)
  setVersion(version)
  const record = c.decode(collection0_enc, valueBuf)
  record.spdxId = key[0]
  return record
}
// '@qvac-main-registry/license' key reconstruction function
function collection0_reconstruct_key (keyBuf) {
  const key = collection0_key.decode(keyBuf)
  return {
    spdxId: key[0]
  }
}

// '@qvac-main-registry/license'
const collection0 = {
  name: '@qvac-main-registry/license',
  id: 0,
  encodeKey (record) {
    const key = [record.spdxId]
    return collection0_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection0_key.encodeRange({
      gt: gt ? collection0_indexify(gt) : null,
      lt: lt ? collection0_indexify(lt) : null,
      gte: gte ? collection0_indexify(gte) : null,
      lte: lte ? collection0_indexify(lte) : null
    })
  },
  encodeValue (version, record) {
    setVersion(version)
    return c.encode(collection0_enc, record)
  },
  trigger: null,
  reconstruct: collection0_reconstruct,
  reconstructKey: collection0_reconstruct_key,
  indexes: []
}

// '@qvac-main-registry/model' collection key
const collection1_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 1 })

function collection1_indexify (record) {
  const arr = []

  const a0 = record.path
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.source
  if (a1 === undefined) return arr
  arr.push(a1)

  return arr
}

// '@qvac-main-registry/model' value encoding
const collection1_enc = getEncoding('@qvac-main-registry/model/hyperdb#1')

// '@qvac-main-registry/model' reconstruction function
function collection1_reconstruct (version, keyBuf, valueBuf) {
  const key = collection1_key.decode(keyBuf)
  setVersion(version)
  const record = c.decode(collection1_enc, valueBuf)
  record.path = key[0]
  record.source = key[1]
  return record
}
// '@qvac-main-registry/model' key reconstruction function
function collection1_reconstruct_key (keyBuf) {
  const key = collection1_key.decode(keyBuf)
  return {
    path: key[0],
    source: key[1]
  }
}

// '@qvac-main-registry/model'
const collection1 = {
  name: '@qvac-main-registry/model',
  id: 1,
  encodeKey (record) {
    const key = [record.path, record.source]
    return collection1_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection1_key.encodeRange({
      gt: gt ? collection1_indexify(gt) : null,
      lt: lt ? collection1_indexify(lt) : null,
      gte: gte ? collection1_indexify(gte) : null,
      lte: lte ? collection1_indexify(lte) : null
    })
  },
  encodeValue (version, record) {
    setVersion(version)
    return c.encode(collection1_enc, record)
  },
  trigger: null,
  reconstruct: collection1_reconstruct,
  reconstructKey: collection1_reconstruct_key,
  indexes: []
}

// '@qvac-main-registry/models-by-engine' collection key
const index2_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 2 })

function index2_indexify (record) {
  const arr = []

  const a0 = record.engine
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.path
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.source
  if (a2 === undefined) return arr
  arr.push(a2)

  return arr
}

// '@qvac-main-registry/models-by-engine'
const index2 = {
  name: '@qvac-main-registry/models-by-engine',
  id: 2,
  encodeKey (record) {
    return index2_key.encode(index2_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index2_key.encodeRange({
      gt: gt ? index2_indexify(gt) : null,
      lt: lt ? index2_indexify(lt) : null,
      gte: gte ? index2_indexify(gte) : null,
      lte: lte ? index2_indexify(lte) : null
    })
  },
  encodeValue: (doc) => index2.collection.encodeKey(doc),
  encodeIndexKeys (record, context) {
    return [index2_key.encode([record.engine, record.path, record.source])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection1.indexes.length,
  collection: collection1
}
collection1.indexes.push(index2)

// '@qvac-main-registry/models-by-name' collection key
const index3_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 3 })

// '@qvac-main-registry/models-by-name' has the following schema defined key map
const index3_map = helpers0.mapPathToName

function index3_indexify (record) {
  const a = record
  return a === undefined ? [] : [a]
}

// '@qvac-main-registry/models-by-name'
const index3 = {
  name: '@qvac-main-registry/models-by-name',
  id: 3,
  encodeKey (record) {
    return index3_key.encode(index3_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index3_key.encodeRange({
      gt: (gt || gt === '') ? index3_indexify(gt) : null,
      lt: (lt || lt === '') ? index3_indexify(lt) : null,
      gte: (gte || gte === '') ? index3_indexify(gte) : null,
      lte: (lte || lte === '') ? index3_indexify(lte) : null
    })
  },
  encodeValue: (doc) => index3.collection.encodeKey(doc),
  encodeIndexKeys (record, context) {
    const mapped = index3_map(record, context)
    const keys = new Array(mapped.length)
    for (let i = 0; i < mapped.length; i++) {
      const mappedRecord = mapped[i]
      keys[i] = index3_key.encode([mappedRecord, record.path, record.source])
    }
    return keys
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection1.indexes.length,
  collection: collection1
}
collection1.indexes.push(index3)

// '@qvac-main-registry/models-by-quantization' collection key
const index4_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 4 })

function index4_indexify (record) {
  const arr = []

  const a0 = record.quantization
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.path
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.source
  if (a2 === undefined) return arr
  arr.push(a2)

  return arr
}

// '@qvac-main-registry/models-by-quantization'
const index4 = {
  name: '@qvac-main-registry/models-by-quantization',
  id: 4,
  encodeKey (record) {
    return index4_key.encode(index4_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index4_key.encodeRange({
      gt: gt ? index4_indexify(gt) : null,
      lt: lt ? index4_indexify(lt) : null,
      gte: gte ? index4_indexify(gte) : null,
      lte: lte ? index4_indexify(lte) : null
    })
  },
  encodeValue: (doc) => index4.collection.encodeKey(doc),
  encodeIndexKeys (record, context) {
    return [index4_key.encode([record.quantization, record.path, record.source])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection1.indexes.length,
  collection: collection1
}
collection1.indexes.push(index4)

// '@qvac-main-registry/models-by-engine-quantization' collection key
const index5_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING,
  IndexEncoder.STRING
], { prefix: 5 })

function index5_indexify (record) {
  const arr = []

  const a0 = record.engine
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.quantization
  if (a1 === undefined) return arr
  arr.push(a1)

  const a2 = record.path
  if (a2 === undefined) return arr
  arr.push(a2)

  const a3 = record.source
  if (a3 === undefined) return arr
  arr.push(a3)

  return arr
}

// '@qvac-main-registry/models-by-engine-quantization'
const index5 = {
  name: '@qvac-main-registry/models-by-engine-quantization',
  id: 5,
  encodeKey (record) {
    return index5_key.encode(index5_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index5_key.encodeRange({
      gt: gt ? index5_indexify(gt) : null,
      lt: lt ? index5_indexify(lt) : null,
      gte: gte ? index5_indexify(gte) : null,
      lte: lte ? index5_indexify(lte) : null
    })
  },
  encodeValue: (doc) => index5.collection.encodeKey(doc),
  encodeIndexKeys (record, context) {
    return [index5_key.encode([record.engine, record.quantization, record.path, record.source])]
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection1.indexes.length,
  collection: collection1
}
collection1.indexes.push(index5)

const collections = [
  collection0,
  collection1
]

const indexes = [
  index2,
  index3,
  index4,
  index5
]

module.exports = { version, collections, indexes, resolveCollection, resolveIndex }

function resolveCollection (name) {
  switch (name) {
    case '@qvac-main-registry/license': return collection0
    case '@qvac-main-registry/model': return collection1
    default: return null
  }
}

function resolveIndex (name) {
  switch (name) {
    case '@qvac-main-registry/models-by-engine': return index2
    case '@qvac-main-registry/models-by-name': return index3
    case '@qvac-main-registry/models-by-quantization': return index4
    case '@qvac-main-registry/models-by-engine-quantization': return index5
    default: return null
  }
}
