#pragma once


#include <functional>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

#include <llama.h>
#include <picojson/picojson.h>

#include "CacheManager.hpp"
#include "LlamaLazyInitializeBackend.hpp"
#include "LlmContext.hpp"
#include "common/chat.h"
#include "qvac-lib-inference-addon-cpp/BlobsStream.hpp"
#include "qvac-lib-inference-addon-cpp/GGUFShards.hpp"
#include "qvac-lib-inference-addon-cpp/InitLoader.hpp"
#include "qvac-lib-inference-addon-cpp/Logger.hpp"
#include "qvac-lib-inference-addon-cpp/RuntimeStats.hpp"

class LlamaModel {
public:
  LlamaModel(const LlamaModel&) = delete;
  LlamaModel& operator=(const LlamaModel&) = delete;
  LlamaModel(LlamaModel&&) = delete;
  LlamaModel& operator=(LlamaModel&&) = delete;
  using Input = std::variant<std::string, std::vector<uint8_t>>;
  using InputView = Input;
  using Output = std::string;

  /**
   * The Constructor for llama model.
   * @param modelPath - path to the model file.
   * @param projectionPath - path to the projector file.
   * @param configFilemap - map of configuration files.
   */
  LlamaModel(
      // NOLINTNEXTLINE(bugprone-easily-swappable-parameters)
      const std::string& modelPath, const std::string& projectionPath,
      std::unordered_map<std::string, std::string>& configFilemap);

  /**
   * The Destructor for llama model.
   * Members are destroyed in reverse order of declaration, ensuring
   * llmContext is destroyed before backendsHandle_.
   */
  ~LlamaModel() = default;

  /// @brief Call for asynchronous loading of file shards.
  void set_weights_for_file( // NOLINT(readability-identifier-naming)
      const std::string& filename,
      std::unique_ptr<std::basic_streambuf<char>>&& shard);

  /**
   * The stop method. It stops the model inference.
   */
  void stop();

  /**
   * The process method. It reserves in input string and generated a reply.
   *
   * @param input - user request from the model in natural language.
   * @param outputCallback - callback function that will be called for each
   * token generated by the model. The callback receives the decoded text for
   * the token as a string parameter. If nullptr, no streaming callback will
   * occur.
   *
   * @return a replay from the model
   */
  Output process(
      const Input& input,
      const std::function<void(const Output&)>& outputCallback = {});

  /**
   * The Reset method.
   */
  void reset() {}

  /**
   * Initialize backend (llama.cpp setup).
   */
  void initializeBackend(const std::string& backendsDir = "");

  /**
   * Check if model is loaded.
   */
  bool isLoaded();

  /**
   * Ensure model is initialized
   */
  void waitForLoadInitialization() {
    initLoader_.waitForLoadInitialization();
  }

    /**
     * The Runtime stats method. It outputs the runtime infernce stats per job.
     *
     * @return inference stats.
     */
    qvac_lib_inference_addon_cpp::RuntimeStats runtimeStats();

    /**
     * Static callback function for llama.cpp logging
     */
    static void
    llamaLogCallback(ggml_log_level level, const char* text, void* userData);

  private:
    /**
     * The Common params parse method. It parses the common params.
     *
     * @param modelPath - model path.
     * @param configFilemap - config file map.
     * @param params - common params.
     */
    void commonParamsParse(
        const std::string& modelPath,
        std::unordered_map<std::string, std::string>& configFilemap,
        common_params& params);

    /**
     * The Format prompt method. It formats the prompt json to chat messages.
     *
     * @param input - input prompt.
     * @return formatted chat messages and tools.
     */
    std::pair<std::vector<common_chat_msg>, std::vector<common_chat_tool>>
    formatPrompt(const std::string& input);

    /**
     * The Reset state method. It resets the model state.
     */
    void resetState(bool resetStats = true);

    /**
     * Create the appropriate context based on model type and projector path
     * @param projectionPath - path to the projector file (for multimodal
     * models)
     * @param params - common parameters
     * @param common_init_result - Result of loading/initializing model from
     * .gguf file(s)
     * @return unique_ptr to the appropriate LlmContext
     */
    std::unique_ptr<LlmContext> createContext(
        const std::string& projectionPath, common_params& params,
        common_init_result&& llamaInit);

    /**
     * The Load media method. It loads the media.
     *
     * @param input - input.
     * @return true if the media is loaded, false otherwise.
     */
    bool loadMedia(const Input& input);

    void init(
        const std::string& modelPath, const std::string& projectionPath,
        std::unordered_map<std::string, std::string>& configFilemap);

    // private members
    const std::string loadingContext_;
    const GGUFShards shards_;
    friend class InitLoader;
    InitLoader initLoader_;

    bool isTextLlm_ = false;
    bool isStreaming_ = false;
    std::map<std::string, std::unique_ptr<std::basic_streambuf<char>>>
        singleGgufStreamedFiles_;

    // Backend handle must be declared before llmContext to ensure
    // llmContext is destroyed first (members destroyed in reverse order)
    std::optional<LlamaBackendsHandle> backendsHandle_;

    // Store the appropriate context (TextLlmContext or MtmdLlmContext)
    // Destroyed before backendsHandle_ to avoid use-after-free
    std::unique_ptr<LlmContext> llmContext_;

    // configuration values parsed from configFilemap
    llama_pos configuredNDiscarded_ = 0;
    std::optional<CacheManager> cacheManager_;
};


