#pragma once

#include <functional>
#include <memory>
#include <optional>
#include <shared_mutex>
#include <string>
#include <string_view>
#include <vector>

#include <llama.h>
#include <picojson/picojson.h>

#include "AsyncWeightsLoader.hpp"
#include "CacheManager.hpp"
#include "LlamaLazyInitializeBackend.hpp"
#include "LlmContext.hpp"
#include "ModelMetadata.hpp"
#include "common/chat.h"
#include "qvac-lib-inference-addon-cpp/BlobsStream.hpp"
#include "qvac-lib-inference-addon-cpp/GGUFShards.hpp"
#include "qvac-lib-inference-addon-cpp/InitLoader.hpp"
#include "qvac-lib-inference-addon-cpp/Logger.hpp"
#include "qvac-lib-inference-addon-cpp/ModelInterfaces.hpp"
#include "qvac-lib-inference-addon-cpp/RuntimeStats.hpp"

using namespace qvac_lib_inference_addon_cpp::model;

class LlamaModel : public IModel, public IModelAsyncLoad, public IModelCancel {
public:
  LlamaModel(const LlamaModel&) = delete;
  LlamaModel& operator=(const LlamaModel&) = delete;
  LlamaModel(LlamaModel&&) = delete;
  LlamaModel& operator=(LlamaModel&&) = delete;

  /// @brief Resolves shard basenames in-place to absolute paths relative to
  /// the parent directory of @p modelPath.
  static void
  resolveShardPaths(GGUFShards& shards, const std::string& modelPath);

  /// @brief Apply specific parameter defaults based on model metadata
  /// and detected Adreno GPU version by inserting entries into configFilemap.
  /// Must be called before commonParamsParse so inserted entries are processed.
  ///
  /// @param configFilemap The user-supplied config map (will be written to).
  /// @param metadata Model metadata (architecture, quantization info).
  /// @param adrenoVersion Detected Adreno GPU version, if any.
  static void tuneConfigMap(
      std::unordered_map<std::string, std::string>& configFilemap,
      const ModelMetaData& metadata, const std::optional<int>& adrenoVersion);

  /**
   * The Constructor for llama model.
   * @param modelPath - path to the model file.
   * @param projectionPath - path to the projector file.
   * @param configFilemap - map of configuration files.
   */
  LlamaModel(
      // NOLINTNEXTLINE(bugprone-easily-swappable-parameters)
      std::string&& modelPath, std::string&& projectionPath,
      std::unordered_map<std::string, std::string>&& configFilemap);

  struct ConstructionArgs {
    std::string modelPath;
    std::string projectionPath;
    std::unordered_map<std::string, std::string> configFilemap;
    InitLoader::LOADER_TYPE loaderType = InitLoader::LOADER_TYPE::DELAYED;
  };

  /**
   * The Destructor for llama model.
   * Members are destroyed in reverse order of declaration, ensuring
   * llmContext_ is destroyed before backendsHandle_.
   */
  ~LlamaModel() override = default;

  std::string getName() const final { return "LlamaModel"; }

  /// @brief Call for asynchronous loading of file shards.
  void setWeightsForFile(
      const std::string& filename,
      std::unique_ptr<std::basic_streambuf<char>>&& shard) final;

  /**
   * The stop method. It stops the model inference.
   */
  void cancel() const final;

  struct Prompt {
    std::string input;
    bool prefill = false;
    std::vector<std::vector<uint8_t>> media;
    std::function<void(const std::string&)> outputCallback;
  };

  std::any process(const std::any& input) final;

  /**
   * The process method. It reserves in input string and generated a reply.
   *
   * @param prompt.input - user request from the model in natural language.
   * @param outputCallback - callback function that will be called for each
   * token generated by the model. The callback receives the decoded text for
   * the token as a string parameter. If nullptr, no streaming callback will
   * occur.
   * @return a replay from the model
   */
  std::string processPrompt(const Prompt& prompt);

  /**
   * The Reset method.
   */
  void reset() {
    std::shared_lock lock(stateMtx_);
    resetState();
  }

  /// @brief Rebuilds reloadable model state using stored construction args.
  /// Acquires exclusive lock on stateMtx_; tries to cancel and blocks until
  /// any in-flight operation that access the state finishes, then safely swaps
  /// the state.
  void reload();

  /**
   * Check if model is loaded.
   */
  bool isLoaded();

  /**
   * Get the number of conversation-only tokens (without tools).
   * This is set when toolsAtEnd is enabled and tools are provided.
   */
  llama_pos getNConversationOnlyTokens() const;

  /**
   * Ensure model is initialized
   */
  void waitForLoadInitialization() final {
    std::shared_ptr<ReloadableState> localState;
    {
      std::shared_lock lock(stateMtx_);
      localState = state_;
    }
    localState->initLoader_.waitForLoadInitialization();
  }

  /**
   * The Runtime stats method. It outputs the runtime infernce stats per job.
   *
   * @return inference stats.
   */
  qvac_lib_inference_addon_cpp::RuntimeStats runtimeStats() const final;

  /**
   * Static callback function for llama.cpp logging
   */
  static void
  llamaLogCallback(ggml_log_level level, const char* text, void* userData);

private:
  // Impl without mutexes
  std::string processPromptImpl(const Prompt& prompt);
  void cancelImpl() const;

  struct ReloadableState {
    ReloadableState(
        const ConstructionArgs& args, const std::string& loadingContext,
        ModelMetaData& metadata)
        : shards_(GGUFShards::expandGGUFIntoShards(args.modelPath)),
          asyncWeightsLoader_(shards_, initLoader_, loadingContext, &metadata) {
    }

    GGUFShards shards_;
    friend class InitLoader;
    InitLoader initLoader_;
    AsyncWeightsLoader asyncWeightsLoader_;

    bool isTextLlm_ = false;

    // Backend handle must be declared before llmContext_ to ensure
    // llmContext_ is destroyed first (members destroyed in reverse order)
    std::optional<LlamaBackendsHandle> backendsHandle_;

    // Store the appropriate context (TextLlmContext or MtmdLlmContext)
    // Destroyed before backendsHandle_ to avoid use-after-free
    std::unique_ptr<LlmContext> llmContext_;

    // configuration values parsed from configFilemap
    llama_pos configuredNDiscarded_ = 0;
    bool toolsAtEnd_ = false;
    std::optional<CacheManager> cacheManager_;
    bool lastRunWasPrefill_ = false;
  };

  struct ResolvedPrompt {
    std::vector<common_chat_msg> chatMsgs;
    std::vector<common_chat_tool> tools;
    bool isCacheLoaded = false;
    bool shouldResetAfterInference = false;
  };
  ResolvedPrompt resolveChatAndTools(const std::string& input);

  /**
   * The Common params parse method. It parses the common params.
   *
   * @param model_path - model path.
   * @param configFilemap - config file map.
   * @param params - common params.
   */
  void commonParamsParse(
      const std::string& modelPath,
      std::unordered_map<std::string, std::string>& configFilemap,
      common_params& params, std::optional<int>& outAdrenoVersion);

  /**
   * The Format prompt method. It formats the prompt json to chat messages.
   *
   * @param input - input prompt.
   * @return formatted chat messages and tools.
   */
  std::pair<std::vector<common_chat_msg>, std::vector<common_chat_tool>>
  formatPrompt(const std::string& input);

  /**
   * The Reset state method. It resets the model state.
   */
  void resetState(bool resetStats = true);

  /**
   * Create the appropriate context based on model type and projector path
   * @param model_path - path to the model file
   * @param params - common parameters
   * @param common_init_result - Result of loading/initializing model from
   * .gguf file(s)
   * @return unique_ptr to the appropriate LlmContext
   */
  std::unique_ptr<LlmContext> createContext(
      std::string&& projectionPath, common_params& params,
      common_init_result&& llamaInit);

  /**
   * The Load media method. It loads the media.
   *
   * @param input - input.
   * @return true if the media is loaded, false otherwise.
   */
  bool loadMedia(const std::vector<uint8_t>& input);

  void setInitLoader(
      std::optional<InitLoader::LOADER_TYPE> loaderType = std::nullopt);

  void init(bool acquireLock);

  const std::string loadingContext_;
  ModelMetaData metadata_;
  ConstructionArgs constructionArgs_;

  /// Shared lock for all methods that read/use state_ members; exclusive lock
  /// only in reload()
  mutable std::shared_mutex stateMtx_;
  std::shared_ptr<ReloadableState> state_;
};
