// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @rag/documents
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.content)
    c.string.preencode(state, m.contentHash)
    c.date.preencode(state, m.createdAt)
    c.date.preencode(state, m.updatedAt)
    state.end++ // max flag is 1 so always one byte

    if (m.metadata) c.json.preencode(state, m.metadata)
  },
  encode(state, m) {
    const flags = m.metadata ? 1 : 0

    c.string.encode(state, m.id)
    c.string.encode(state, m.content)
    c.string.encode(state, m.contentHash)
    c.date.encode(state, m.createdAt)
    c.date.encode(state, m.updatedAt)
    c.uint.encode(state, flags)

    if (m.metadata) c.json.encode(state, m.metadata)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.date.decode(state)
    const r4 = c.date.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      content: r1,
      contentHash: r2,
      createdAt: r3,
      updatedAt: r4,
      metadata: (flags & 1) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @rag/vectors
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.docId)
    c.json.preencode(state, m.vector)
    c.date.preencode(state, m.createdAt)
  },
  encode(state, m) {
    c.string.encode(state, m.docId)
    c.json.encode(state, m.vector)
    c.date.encode(state, m.createdAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.json.decode(state)
    const r2 = c.date.decode(state)

    return {
      docId: r0,
      vector: r1,
      createdAt: r2
    }
  }
}

// @rag/centroids
const encoding2 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.json.preencode(state, m.vector)
    c.uint32.preencode(state, m.index)
    c.date.preencode(state, m.createdAt)
  },
  encode(state, m) {
    c.string.encode(state, m.id)
    c.json.encode(state, m.vector)
    c.uint32.encode(state, m.index)
    c.date.encode(state, m.createdAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.json.decode(state)
    const r2 = c.uint32.decode(state)
    const r3 = c.date.decode(state)

    return {
      id: r0,
      vector: r1,
      index: r2,
      createdAt: r3
    }
  }
}

// @rag/ivfBuckets
const encoding3 = {
  preencode(state, m) {
    c.string.preencode(state, m.centroidId)
    c.json.preencode(state, m.documentIds)
    c.uint32.preencode(state, m.capacity)
    c.date.preencode(state, m.createdAt)
    c.date.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    c.string.encode(state, m.centroidId)
    c.json.encode(state, m.documentIds)
    c.uint32.encode(state, m.capacity)
    c.date.encode(state, m.createdAt)
    c.date.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.json.decode(state)
    const r2 = c.uint32.decode(state)
    const r3 = c.date.decode(state)
    const r4 = c.date.decode(state)

    return {
      centroidId: r0,
      documentIds: r1,
      capacity: r2,
      createdAt: r3,
      updatedAt: r4
    }
  }
}

// @rag/config
const encoding4 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.string.preencode(state, m.embeddingModelId)
    c.uint32.preencode(state, m.dimension)
    c.uint32.preencode(state, m.NUM_CENTROIDS)
    c.uint32.preencode(state, m.BUCKET_SIZE)
    c.uint32.preencode(state, m.BATCH_SIZE)
    c.date.preencode(state, m.createdAt)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
    c.string.encode(state, m.embeddingModelId)
    c.uint32.encode(state, m.dimension)
    c.uint32.encode(state, m.NUM_CENTROIDS)
    c.uint32.encode(state, m.BUCKET_SIZE)
    c.uint32.encode(state, m.BATCH_SIZE)
    c.date.encode(state, m.createdAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.uint32.decode(state)
    const r3 = c.uint32.decode(state)
    const r4 = c.uint32.decode(state)
    const r5 = c.uint32.decode(state)
    const r6 = c.date.decode(state)

    return {
      key: r0,
      embeddingModelId: r1,
      dimension: r2,
      NUM_CENTROIDS: r3,
      BUCKET_SIZE: r4,
      BATCH_SIZE: r5,
      createdAt: r6
    }
  }
}

// @rag/documents/hyperdb#0
const encoding5 = {
  preencode(state, m) {
    c.string.preencode(state, m.content)
    c.string.preencode(state, m.contentHash)
    c.date.preencode(state, m.createdAt)
    c.date.preencode(state, m.updatedAt)
    state.end++ // max flag is 1 so always one byte

    if (m.metadata) c.json.preencode(state, m.metadata)
  },
  encode(state, m) {
    const flags = m.metadata ? 1 : 0

    c.string.encode(state, m.content)
    c.string.encode(state, m.contentHash)
    c.date.encode(state, m.createdAt)
    c.date.encode(state, m.updatedAt)
    c.uint.encode(state, flags)

    if (m.metadata) c.json.encode(state, m.metadata)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.date.decode(state)
    const r4 = c.date.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      content: r1,
      contentHash: r2,
      createdAt: r3,
      updatedAt: r4,
      metadata: (flags & 1) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @rag/vectors/hyperdb#1
const encoding6 = {
  preencode(state, m) {
    c.json.preencode(state, m.vector)
    c.date.preencode(state, m.createdAt)
  },
  encode(state, m) {
    c.json.encode(state, m.vector)
    c.date.encode(state, m.createdAt)
  },
  decode(state) {
    const r1 = c.json.decode(state)
    const r2 = c.date.decode(state)

    return {
      docId: null,
      vector: r1,
      createdAt: r2
    }
  }
}

// @rag/centroids/hyperdb#2
const encoding7 = {
  preencode(state, m) {
    c.json.preencode(state, m.vector)
    c.uint32.preencode(state, m.index)
    c.date.preencode(state, m.createdAt)
  },
  encode(state, m) {
    c.json.encode(state, m.vector)
    c.uint32.encode(state, m.index)
    c.date.encode(state, m.createdAt)
  },
  decode(state) {
    const r1 = c.json.decode(state)
    const r2 = c.uint32.decode(state)
    const r3 = c.date.decode(state)

    return {
      id: null,
      vector: r1,
      index: r2,
      createdAt: r3
    }
  }
}

// @rag/ivfBuckets/hyperdb#3
const encoding8 = {
  preencode(state, m) {
    c.json.preencode(state, m.documentIds)
    c.uint32.preencode(state, m.capacity)
    c.date.preencode(state, m.createdAt)
    c.date.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    c.json.encode(state, m.documentIds)
    c.uint32.encode(state, m.capacity)
    c.date.encode(state, m.createdAt)
    c.date.encode(state, m.updatedAt)
  },
  decode(state) {
    const r1 = c.json.decode(state)
    const r2 = c.uint32.decode(state)
    const r3 = c.date.decode(state)
    const r4 = c.date.decode(state)

    return {
      centroidId: null,
      documentIds: r1,
      capacity: r2,
      createdAt: r3,
      updatedAt: r4
    }
  }
}

// @rag/config/hyperdb#5
const encoding9 = {
  preencode(state, m) {
    c.string.preencode(state, m.embeddingModelId)
    c.uint32.preencode(state, m.dimension)
    c.uint32.preencode(state, m.NUM_CENTROIDS)
    c.uint32.preencode(state, m.BUCKET_SIZE)
    c.uint32.preencode(state, m.BATCH_SIZE)
    c.date.preencode(state, m.createdAt)
  },
  encode(state, m) {
    c.string.encode(state, m.embeddingModelId)
    c.uint32.encode(state, m.dimension)
    c.uint32.encode(state, m.NUM_CENTROIDS)
    c.uint32.encode(state, m.BUCKET_SIZE)
    c.uint32.encode(state, m.BATCH_SIZE)
    c.date.encode(state, m.createdAt)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.uint32.decode(state)
    const r3 = c.uint32.decode(state)
    const r4 = c.uint32.decode(state)
    const r5 = c.uint32.decode(state)
    const r6 = c.date.decode(state)

    return {
      key: null,
      embeddingModelId: r1,
      dimension: r2,
      NUM_CENTROIDS: r3,
      BUCKET_SIZE: r4,
      BATCH_SIZE: r5,
      createdAt: r6
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@rag/documents':
      return encoding0
    case '@rag/vectors':
      return encoding1
    case '@rag/centroids':
      return encoding2
    case '@rag/ivfBuckets':
      return encoding3
    case '@rag/config':
      return encoding4
    case '@rag/documents/hyperdb#0':
      return encoding5
    case '@rag/vectors/hyperdb#1':
      return encoding6
    case '@rag/centroids/hyperdb#2':
      return encoding7
    case '@rag/ivfBuckets/hyperdb#3':
      return encoding8
    case '@rag/config/hyperdb#5':
      return encoding9
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
