#!/usr/bin/env bash
#
# .agent/setup.sh — Configure agent tooling for Claude Code and/or Cursor
#
# Usage: .agent/setup.sh [claude|cursor|all]
#
# Copies shared config from .agent/ into agent-specific directories.
# Idempotent — safe to re-run anytime. No symlinks (Windows compat).
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

HEADER="<!-- AUTO-GENERATED by .agent/setup.sh — do not edit directly. Edit the source in .agent/ instead. -->"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
copy_with_header() {
  local src="$1"
  local dst="$2"
  mkdir -p "$(dirname "$dst")"
  printf '%s\n\n' "$HEADER" > "$dst"
  cat "$src" >> "$dst"
  echo "  copied: $dst"
}

copy_plain() {
  local src="$1"
  local dst="$2"
  mkdir -p "$(dirname "$dst")"
  cp "$src" "$dst"
  echo "  copied: $dst"
}

strip_yaml_frontmatter() {
  # Remove YAML frontmatter (--- ... ---) from the beginning of a file
  awk '
    BEGIN { in_front=0; found=0 }
    NR==1 && /^---\s*$/ { in_front=1; next }
    in_front && /^---\s*$/ { in_front=0; found=1; next }
    in_front { next }
    found && NR>1 && /^\s*$/ && !printed { next }
    { printed=1; print }
  ' "$1"
}

wrap_with_frontmatter() {
  local src="$1"
  local name="$2"
  local description="$3"
  local dst="$4"
  mkdir -p "$(dirname "$dst")"
  {
    printf '%s\n\n' "$HEADER"
    printf -- '---\nname: %s\ndescription: %s\n---\n\n' "$name" "$description"
    cat "$src"
  } > "$dst"
  echo "  copied: $dst (with frontmatter)"
}

# ---------------------------------------------------------------------------
# Setup: Claude Code
# ---------------------------------------------------------------------------
setup_claude() {
  echo ""
  echo "Setting up Claude Code (.claude/)..."

  # Conduct
  copy_with_header "$SCRIPT_DIR/conduct.md" "$REPO_ROOT/.claude/agent-conduct.md"

  # Knowledge
  for f in "$SCRIPT_DIR"/knowledge/*.md; do
    [ -f "$f" ] || continue
    copy_with_header "$f" "$REPO_ROOT/.claude/knowledge/$(basename "$f")"
  done

  # Skills (directory-based: each skill is a dir with SKILL.md + optional supporting files)
  for skill_dir in "$SCRIPT_DIR"/skills/*/; do
    [ -d "$skill_dir" ] || continue
    skill_name="$(basename "$skill_dir")"
    # Copy SKILL.md
    if [ -f "$skill_dir/SKILL.md" ]; then
      copy_plain "$skill_dir/SKILL.md" "$REPO_ROOT/.claude/skills/$skill_name/SKILL.md"
    fi
    # Copy supporting files (everything except SKILL.md)
    find "$skill_dir" -type f ! -name "SKILL.md" | while read -r f; do
      rel="${f#$skill_dir}"
      copy_plain "$f" "$REPO_ROOT/.claude/skills/$skill_name/$rel"
    done
  done

  # MCP: print instructions (Claude Code uses user-level config)
  echo ""
  echo "  MCP servers are defined in .agent/mcp.json."
  echo "  To configure Claude Code, add them to ~/.claude/settings.json under 'mcpServers'."
  echo "  See .agent/mcp.json for the server definitions."
  echo ""
  echo "Claude Code setup complete."
}

# ---------------------------------------------------------------------------
# Setup: Cursor
# ---------------------------------------------------------------------------
setup_cursor() {
  echo ""
  echo "Setting up Cursor (.cursor/)..."

  # Skills (directory-based: copy all skills to Cursor)
  for skill_dir in "$SCRIPT_DIR"/skills/*/; do
    [ -d "$skill_dir" ] || continue
    skill_name="$(basename "$skill_dir")"
    # Copy SKILL.md
    if [ -f "$skill_dir/SKILL.md" ]; then
      copy_plain "$skill_dir/SKILL.md" "$REPO_ROOT/.cursor/skills/$skill_name/SKILL.md"
    fi
    # Copy supporting files (everything except SKILL.md)
    find "$skill_dir" -type f ! -name "SKILL.md" | while read -r f; do
      rel="${f#$skill_dir}"
      copy_plain "$f" "$REPO_ROOT/.cursor/skills/$skill_name/$rel"
    done
  done

  # MCP: generate .cursor/mcp.json from .agent/mcp.json
  # Cursor uses mcpServers at the top level (not nested under "servers")
  node -e "
    const src = require('$SCRIPT_DIR/mcp.json');
    const out = { mcpServers: src.servers };
    process.stdout.write(JSON.stringify(out, null, 2) + '\n');
  " > "$REPO_ROOT/.cursor/mcp.json"
  echo "  generated: .cursor/mcp.json"

  echo ""
  echo "Cursor setup complete."
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
target="${1:-all}"

echo "=== Agent Config Setup ==="
echo "Source: .agent/"
echo "Target: $target"

case "$target" in
  claude)
    setup_claude
    ;;
  cursor)
    setup_cursor
    ;;
  all)
    setup_claude
    setup_cursor
    ;;
  *)
    echo "Usage: .agent/setup.sh [claude|cursor|all]"
    exit 1
    ;;
esac

echo ""
echo "Done. Generated files are marked AUTO-GENERATED — edit sources in .agent/ instead."
