// Auto-generated by scripts/update-versions-list.ts
// DO NOT EDIT MANUALLY - Changes will be overwritten

export interface Version {
  label: string;
  path: string;
  isLatest?: boolean;
}

export const VERSIONS: Version[] = [
  { label: 'Latest (v0.7.0)', path: 'latest', isLatest: true },
  { label: 'v0.7.0', path: 'v0.7.0' },
  { label: 'v0.6.1', path: 'v0.6.1' },
  { label: 'v0.6.0', path: 'v0.6.0' },
  { label: 'v0.5.0', path: 'v0.5.0' },
];

export const LATEST_VERSION = 'v0.7.0';

/**
 * Extract version from URL pathname
 * @example getVersionFromPath('/docs/sdk/api/v0.6.1/loadModel') → 'v0.6.1'
 */
export function getVersionFromPath(pathname: string): string | null {
  const match = pathname.match(/\/docs\/sdk\/api\/(v[\d.]+|latest)\//);
  return match?.[1] ?? null;
}
