name: Approval Check Worker

on:
  pull_request_review:
    types: [submitted]
    
jobs:
  check-approvals:
    if: github.event.review.state == 'approved'
    permissions:
      contents: write
      pull-requests: write
      statuses: write
      issues: write
    uses: tetherto/qvac-devops/.github/workflows/approval-check-worker.yml@monorepo_update
    secrets: inherit
    with:
      pr_number: ${{ github.event.pull_request.number }}
      pr_sha: ${{ github.sha }}
