name: On Merge Trigger (OCR)

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - "packages/qvac-lib-inference-addon-onnx-ocr-fasttext/**"

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  prebuild-main:
    if: github.ref_name == 'main'
    uses: ./.github/workflows/prebuilds-qvac-lib-inference-addon-onnx-ocr-fasttext.yml
    secrets: inherit
    with:
      publish_target: "gpr"

  run-integration-tests:
    needs: prebuild-main
    if: github.ref_name == 'main'
    uses: ./.github/workflows/integration-test-qvac-lib-inference-addon-onnx-ocr-fasttext.yml
    secrets: inherit

  prebuild-release:
    if: startsWith(github.ref_name, 'release-')
    uses: ./.github/workflows/prebuilds-qvac-lib-inference-addon-onnx-ocr-fasttext.yml
    secrets: inherit
    with:
      publish_target: "npm"