name: On PR Trigger (LLM)

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    branches:
      - main
      - release-*
      - feature-*
      - tmp-*
    paths:
      - "packages/qvac-lib-infer-llamacpp-llm/**"
      - ".github/workflows/*llamacpp-llm*.yml"
  workflow_dispatch:

  workflow_call:

permissions:
  contents: read
  pull-requests: read
  packages: read

jobs:
  on-pr:
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/_reusable-on-pr-addon.yml
    secrets: inherit
    with:
      package_slug: qvac-lib-infer-llamacpp-llm
      workdir: packages/qvac-lib-infer-llamacpp-llm
      artifact_prefix: llama-cpp
      test_models: >-
        [
          "bartowski/Llama-3.2-1B-Instruct-GGUF/Llama-3.2-1B-Instruct-Q4_0.gguf",
          "ggml-org/SmolVLM2-500M-Video-Instruct-GGUF/SmolVLM2-500M-Video-Instruct-Q8_0.gguf=SmolVLM-500M-Instruct-Q8_0.gguf",
          "ggml-org/SmolVLM2-500M-Video-Instruct-GGUF/mmproj-SmolVLM2-500M-Video-Instruct-Q8_0.gguf=mmproj-SmolVLM-500M-Instruct-Q8_0.gguf",
          "Qwen/Qwen3-0.6B-GGUF/Qwen3-0.6B-Q8_0.gguf",
          "jmb95/Qwen3-0.6B-UD-IQ1_S-sharded/Qwen3-0.6B-UD-IQ1_S-%05d-of-%05d.gguf*3",
          "jmb95/Qwen3-0.6B-UD-IQ1_S-sharded/Qwen3-0.6B-UD-IQ1_S.tensors.txt",
          "gianni-cor/bitnet_b1_58-large-TQ2_0/bitnet_b1_58-large-TQ2_0.gguf",
          "jmb95/bitnet_b1_58-large-TQ2_0-sharded/bitnet_b1_58-large-TQ2_0-%05d-of-%05d.gguf*8",
          "jmb95/bitnet_b1_58-large-TQ2_0-sharded/bitnet_b1_58-large-TQ2_0.tensors.txt"
        ]

  run-integration-tests:
    needs: on-pr
    permissions:
      contents: read
      packages: read
      id-token: write
    uses: ./.github/workflows/integration-test-qvac-lib-infer-llamacpp-llm.yml
    secrets: inherit
    with:
      repository: ${{ github.event.pull_request.head.repo.full_name }}
      ref: ${{ github.event.pull_request.head.ref }}

  run-mobile-integration-tests:
    needs: on-pr
    permissions:
      contents: read
      packages: read
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/integration-mobile-test-qvac-lib-infer-llamacpp-llm.yml
    secrets: inherit
    with:
      repository: ${{ github.event.pull_request.head.repo.full_name }}
      ref: ${{ github.event.pull_request.head.ref }}

  merge-guard:
    needs: [on-pr, run-integration-tests, run-mobile-integration-tests]
    if: always()
    uses: tetherto/qvac-devops/.github/workflows/public-pr.yml@v1.1.8
    with:
      sanity-checks-status: ${{ needs.on-pr.result == 'success' }}
      build-status: ${{ needs.on-pr.result == 'success' }}
