name: On PR Trigger (Embed)

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    branches:
      - main
      - release-*
      - feature-*
      - tmp-*
    paths:
      - "packages/qvac-lib-infer-llamacpp-embed/**"
      - ".github/workflows/*embed*.yml"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  packages: read

jobs:
  on-pr:
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/_reusable-on-pr-addon.yml
    secrets: inherit
    with:
      package_slug: qvac-lib-infer-llamacpp-embed
      workdir: packages/qvac-lib-infer-llamacpp-embed
      artifact_prefix: llama-cpp
      test_models: >-
        [
          "unsloth/embeddinggemma-300m-GGUF/embeddinggemma-300M-Q8_0.gguf=test-model.gguf"
        ]

  integration-tests:
    needs: on-pr
    permissions:
      contents: read
      packages: read
      id-token: write
    uses: ./.github/workflows/integration-test-qvac-lib-infer-llamacpp-embed.yml
    secrets: inherit
    with:
      repository: ${{ github.event.pull_request.head.repo.full_name }}
      ref: ${{ github.event.pull_request.head.ref }}

  run-mobile-integration-tests:
    needs: on-pr
    permissions:
      contents: read
      packages: read
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/integration-mobile-test-qvac-lib-infer-llamacpp-embed.yml
    secrets: inherit
    with:
      repository: ${{ github.event.pull_request.head.repo.full_name }}
      ref: ${{ github.event.pull_request.head.ref }}

  merge-guard:
    needs: [on-pr, integration-tests, run-mobile-integration-tests]
    if: always()
    uses: tetherto/qvac-devops/.github/workflows/public-pr.yml@v1.1.8
    with:
      sanity-checks-status: ${{ needs.on-pr.result == 'success' }}
      build-status: ${{ needs.on-pr.result == 'success' }}
