name: Unpublish GPR (VAD)
on:
  pull_request:
    types:
      - closed
    paths:
      - "packages/qvac-lib-infer-onnx-vad/**"
  workflow_dispatch:
    inputs:
      version:
        description: "Specific version to target for deletion"
        required: false
        type: string
      pr-number:
        description: "PR number to target for deletion"
        required: false
        type: string
      pattern:
        description: "Pattern to target for deletion"
        required: false
        type: string
      packages:
        description: "Packages to target for deletion, space separated"
        required: false
        type: string
        default: "qvac-lib-inference-addon-onnx-silerovad"
      dry-run:
        description: "Is dry run? If true, lists versions without deleting."
        type: boolean
        default: true

run-name: Delete NPM Versions ${{ inputs.version }} ${{ inputs.pr-number }} ${{ inputs.dry-run }}

permissions:
  contents: read
  packages: write
  
jobs:
  print-context:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: |
          echo "Inputs Context: $INPUTS_CONTEXT"
        env:
          INPUTS_CONTEXT: ${{ toJSON(inputs) }}
      - run: |
          echo "GitHub Context: $GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}

  delete-npm-versions-trigger:
    uses: tetherto/qvac-devops/.github/workflows/public-delete-npm-versions.yml@monorepo_update
    with:
      version: ${{ inputs.version }}
      pr-number: ${{ inputs.pr-number }}
      pattern: ${{ inputs.pattern }}
      packages: ${{ inputs.packages }}
      dry-run: ${{ inputs.dry-run || true }}
    secrets: inherit
