name: On PR Trigger (NMTCPP)

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    branches:
      - main
      - release-*
      - feature-*
      - tmp-*
    paths:
      - "packages/qvac-lib-infer-nmtcpp/**"
      - ".github/workflows/*nmtcpp*.yml"
  workflow_dispatch:

concurrency:
  group: pr-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  packages: write

env:
  PKG_DIR: packages/qvac-lib-infer-nmtcpp

jobs:
  changes:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      pkg: ${{ steps.filter.outputs.pkg }}
    steps:
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # 4.0.1
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            pkg:
              - "packages/qvac-lib-infer-nmtcpp/**"
              - ".github/workflows/*nmtcpp*.yml"

  sanity-checks:
    needs: changes
    if: always() && ((needs.changes.outputs.pkg == 'true' && contains(github.event.pull_request.labels.*.name, 'verify')) || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
      - name: Run Sanity checks
        uses: tetherto/qvac-devops/.github/actions/sanity-checks@v1.1.6
        with:
          secret-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          pat-token: ${{ secrets.PAT_TOKEN }}
          run-integration: ${{ contains(github.event.pull_request.labels.*.name, 'verify') }}
          workdir: packages/qvac-lib-infer-nmtcpp

  ts-checks:
    needs: [changes, sanity-checks]
    if: always() && (needs.changes.outputs.pkg == 'true' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PKG_DIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # 6.3.0
        with:
          node-version: 20

      - name: Configure npm auth
        run: |
          qvac_registry="https://registry.npmjs.org/"
          cat > .npmrc <<NPMRC
          registry=https://registry.npmjs.org/
          @qvac:registry=${qvac_registry}
          @tetherto:registry=https://npm.pkg.github.com/
          //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
          NPMRC

      - name: Install dependencies
        run: npm install

      - name: Type declaration check
        run: npm run test:dts

  cpp-lint:
    needs: [changes, sanity-checks]
    if: |
      always() &&
      ((needs.changes.outputs.pkg == 'true' &&
        contains(github.event.pull_request.labels.*.name, 'verify')) ||
       github.event_name == 'workflow_dispatch')
    uses: tetherto/qvac-devops/.github/workflows/cpp-lint.yaml@v1.1.6
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      sha: ${{ github.event.pull_request.base.sha || github.event.before || 'HEAD~1' }}
      pr_head_sha: ${{ github.event.pull_request.head.sha || github.sha }}
      workdir: packages/qvac-lib-infer-nmtcpp

  cpp-tests:
    needs: [changes, sanity-checks]
    if: |
      always() &&
      ((needs.changes.outputs.pkg == 'true' &&
        contains(github.event.pull_request.labels.*.name, 'verify')) ||
       github.event_name == 'workflow_dispatch')
    uses: ./.github/workflows/reusable-cpp-tests-qvac-lib-infer-nmtcpp.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      MODEL_S3_BUCKET: ${{ secrets.MODEL_S3_BUCKET }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
    with:
      ref: ${{ github.event.pull_request.head.ref }}
      repository: ${{ github.event.pull_request.head.repo.full_name }}

  prebuild:
    needs: [changes, sanity-checks]
    if: |
      always() &&
      (needs.changes.outputs.pkg == 'true' || github.event_name == 'workflow_dispatch') &&
      (
        github.event_name == 'workflow_dispatch' ||
        contains(github.event.pull_request.labels.*.name, 'verify')
      )
    uses: ./.github/workflows/prebuilds-qvac-lib-infer-nmtcpp.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MODEL_S3_BUCKET: ${{ secrets.MODEL_S3_BUCKET }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
    with:
      repository: ${{ github.event.pull_request.head.repo.full_name }}
      ref: ${{ github.event.pull_request.head.ref }}
      tag: "dev"
      publish_target: "gpr"

  run-integration-tests:
    needs: [changes, sanity-checks, prebuild]
    if: |
      always() &&
      (needs.changes.outputs.pkg == 'true' || github.event_name == 'workflow_dispatch') &&
      (
        github.event_name == 'workflow_dispatch' ||
        contains(github.event.pull_request.labels.*.name, 'verify')
      )
    uses: ./.github/workflows/integration-test-qvac-lib-infer-nmtcpp.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MODEL_S3_BUCKET: ${{ secrets.MODEL_S3_BUCKET }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
    with:
      repository: ${{ github.event.pull_request.head.repo.full_name }}
      ref: ${{ github.event.pull_request.head.ref }}

  run-mobile-integration-tests:
    needs: [changes, sanity-checks, prebuild]
    if: |
      always() &&
      (needs.changes.outputs.pkg == 'true' || github.event_name == 'workflow_dispatch') &&
      (
        github.event_name == 'workflow_dispatch' ||
        contains(github.event.pull_request.labels.*.name, 'verify')
      )
    uses: ./.github/workflows/integration-mobile-test-qvac-lib-infer-nmtcpp.yml
    secrets:
      ANDROID_DEVICE_POOL_ARN_NMTCPP: ${{ secrets.ANDROID_DEVICE_POOL_ARN_NMTCPP }}
      APPLE_KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
      APPLE_P12_PASSWORD: ${{ secrets.APPLE_P12_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEVICE_FARM_PROJECT_ARN_NMTCPP: ${{ secrets.AWS_DEVICE_FARM_PROJECT_ARN_NMTCPP }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IOS_DEVICE_POOL_ARN_NMTCPP: ${{ secrets.IOS_DEVICE_POOL_ARN_NMTCPP }}
      MODEL_S3_BUCKET: ${{ secrets.MODEL_S3_BUCKET }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      TEST_APP_APPLE_DISTRIBUTION_CERTIFICATE: ${{ secrets.TEST_APP_APPLE_DISTRIBUTION_CERTIFICATE }}
      TEST_APP_APPLE_PROVISIONING_PROFILE: ${{ secrets.TEST_APP_APPLE_PROVISIONING_PROFILE }}
    with:
      repository: ${{ github.event.pull_request.head.repo.full_name }}
      ref: ${{ github.event.pull_request.head.ref }}

  merge-guard:
    needs:
      [
        changes,
        sanity-checks,
        ts-checks,
        cpp-lint,
        cpp-tests,
        prebuild,
        run-integration-tests,
        run-mobile-integration-tests,
      ]
    if: always() && (needs.changes.outputs.pkg == 'true' || github.event_name == 'workflow_dispatch')
    uses: tetherto/qvac-devops/.github/workflows/public-pr.yml@v1.1.6
    with:
      sanity-checks-status: ${{ needs.sanity-checks.result == 'success' && needs.cpp-tests.result == 'success' && needs.ts-checks.result == 'success' }}
      build-status: ${{ needs.prebuild.result == 'success' }}
      integration-tests-status: ${{ needs.run-integration-tests.result == 'success' }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
