name: On PR Close (Decoder-audio)

on:
  push:
    branches:
      - feat/tmp
    
jobs:
  delete-npm-versions-trigger:
    uses: tetherto/qvac-devops/.github/workflows/public-delete-npm-versions.yml@fix/gh-token-secrets
    with:
      version: ${{ inputs.version }}
      pr-number: ${{ github.event_name == 'pull_request' && github.event.pull_request.number || inputs.pr-number }}
      pattern: ${{ inputs.pattern }}
      packages: ${{ inputs.packages || 'qvac-lib-decoder-audio' }}
      dry-run: ${{ github.event_name == 'pull_request' && true || inputs.dry-run }}
    